version: '3.8'
services:
  postgres:
    image: postgres
    container_name: some-postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pfe
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  ms-theme:
    image: ms-theme:latest
    container_name: ms-theme
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pfe
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8083:8080"
    depends_on:
      - postgres
    networks:
      - microservices-network

volumes:
  postgres-data:

networks:
  microservices-network:
    driver: bridge