server:
  port: 7777

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: route1
          predicates:
            - Path=/service-admin/**
          filters:
            - RewritePath=/service-admin/(?<s>.*),/${s}
          uri: lb://ms-administration
        - id: route2
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<s>.*),/${s}
          uri: lb://ms-authentication
        - id: route3
          predicates:
            - Path=/project-theme/**
          filters:
            - RewritePath=/project-theme/(?<s>.*),/${s}
          uri: lb://ms-theme
        - id: route4
          predicates:
            - Path=/monitoring/**
          filters:
            - RewritePath=/monitoring/(?<s>.*),/${s}
          uri: lb://ms-evaluation-monitoring-project

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: localhost:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
