server:
  port: 7777

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: route1
          predicates:
            - Path=/service-admin/**
          filters:
            - RewritePath=/service-admin/(?<s>.*),/${s}
          uri: lb://ms-administration

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: localhost:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka